[package]
name = "loopana"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
nom = "7.1.3"
serde = "1.0.215"
serde_derive = "1.0.215"
serde_yaml = "0.9.34"
pass_derive = { path = "pass_derive" }
